twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        google_analytics: '%env(GOOGLE_ANALYTICS)%'
    paths:
        - "%kernel.project_dir%/templates"
        - "%kernel.project_dir%/src/PHPDocker/Template"
