#index:
#    path: /
#    controller: App\Controller\DefaultController::index

contact:
  path: /contact
  controller: App\Controller\ContactController::process
  methods: ['POST']

generator_get_options:
  path: /generator
  controller: App\Controller\GeneratorController::getGeneratorOptions
  methods: ['GET']

generator_generate:
  path: /generator
  controller: App\Controller\GeneratorController::generate
  methods: ['POST']
