###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.4"
services:

    memcached:
      image: memcached:alpine

    mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "10001:8025"

    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root-password
        - MYSQL_DATABASE=phpdockerio
        - MYSQL_USER=username
        - MYSQL_PASSWORD=password
      ports:
        - "10002:3306"

    postgres:
        image: postgres:9.6-alpine
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=phpdockerio

    webserver:
        image: pagespeed/nginx-pagespeed:stable
        working_dir: /application
        volumes:
            - .:/application
            - ./infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./infrastructure/local/:/etc/ssl/local/
        ports:
            - "10000:443"

    php-fpm:
        build:
            dockerfile: Dockerfile
            target: backend-dev
            context: .
        environment:
            - SYMFONY_ENV=dev
            - APP_ENV=dev
            - APP_SECRET=ThisTokenIsNotSoSecretChangeIt
            - DB_HOST=postgres
            - DB_NAME=phpdockerio
            - DB_USER=username
            - DB_PASSWORD=password

            - MAILER_TRANSPORT=smtp
            - MAILER_HOST=mailhog
            - MAILER_PORT=1025
            - MAILER_USER=""
            - MAILER_PASSWORD=""

            - CONTACT_EMAIL_TO=luis.pabon@auronconsulting.co.uk
            - CONTACT_EMAIL_FROM=automaton@auronconsulting.co.uk
            - CONTACT_EMAIL_SUBJECT="PHPDocker.io - Contact request"

            - GOOGLE_ANALYTICS=foo
            - RECAPTCHA_SITE_KEY=foo
            - RECAPTCHA_SECRET_KEY=bar

            - ADMIN_USER=luis
            - ADMIN_PASSWORD="$$2y$$12$$jS7zyap2VzijFYr8fWn5WuoHrfZMdPzmfTuVUFJ7NAkQb.ZZc6VL"
            - MEMCACHED_HOST=memcached
            - MEMCACHED_PORT=11211
            - CACHE_NAMESPACE=foo
        working_dir: /application
        volumes:
            - .:/application
            - ./infrastructure/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
            - ~/.cache/composer:/root/.composer/cache
