imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc
    serializer:
        cache: serializer.mapping.cache.apc

doctrine:
    orm:
        metadata_cache_driver:
            type: apc
            namespace: "%cache_namespace%"

        result_cache_driver:
            type: memcached
            namespace: "%cache_namespace%"
            host: "%memcached_host%"
            port: "%memcached_port%"

        query_cache_driver:
            type: apc
            namespace: "%cache_namespace%"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "php://stdout"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
