home:
  path:      /
  defaults:
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: /generator
    permanent: true

generator:
  path:      /generator
  defaults:  { _controller: AppBundle:Generator:create }
  methods: [GET, POST]

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /site-admin
