parameters:
    recaptcha_verify_token_endpoint: https://www.google.com/recaptcha/api/siteverify

services:
    docker_generator:
        class:    PHPDocker\Generator\Generator
        factory: [PHPDocker\Generator\Factory, create]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.custom_extensions:
        class: AppBundle\Services\TwigCustomExtensions
        tags:
            - { name: twig.extension }

    cocur_slugify:
        class: Cocur\Slugify\Slugify

    slugifier:
        class: AppBundle\Services\Slugifier
        arguments: ['@cocur_slugify']
