#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
  path:      /
  defaults:
    path: /generator
    permanent: true

generator:
  path:      /generator
  controller: App\Controller\GeneratorController::create
  methods: [GET, POST]
