# See https://github.com/idev4u/concourse-ci-kube
kind: Namespace
apiVersion: v1
metadata:
  name: phpdocker-io-old
  labels:
    name: phpdocker-io-old

---

apiVersion: v1
kind: Service
metadata:
  name: phpdocker-io-old
  namespace: phpdocker-io-old
  labels:
    app: phpdocker-io-old
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: phpdocker-io-old

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: phpdocker-io-old
  namespace: phpdocker-io-old
data:
  dummy: yes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpdocker-io-old
  namespace: phpdocker-io-old
  labels:
    app: phpdocker-io-old
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: phpdocker-io-old
  template:
    metadata:
      labels:
        app: phpdocker-io-old
    spec:
      nodeSelector:
        preemptible: "false"
      containers:
        - image: eu.gcr.io/auron-infrastructure/phpdocker-old-nginx:latest
          name: nginx

        - image: eu.gcr.io/auron-infrastructure/phpdocker-old-php-fpm:latest
          name: php-fpm

          env:
            - name: APP_ENV
              value: prod

            - name: SYMFONY_ENV
              value: prod

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: phpdocker-io-old
                  key: app.secret

            - name: MEMCACHED_HOST
              valueFrom:
                configMapKeyRef:
                  name: phpdocker-io-old
                  key: memcached.host

            - name: MEMCACHED_PORT
              valueFrom:
                configMapKeyRef:
                  name: phpdocker-io-old
                  key: memcached.port

            - name: CACHE_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: phpdocker-io-old
                  key: cache_namespace

            - name: GOOGLE_ANALYTICS
              valueFrom:
                secretKeyRef:
                  name: phpdocker-io-old
                  key: google_analytics

            - name: RECAPTCHA_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: phpdocker-io-old
                  key: recaptcha.site_key

---

apiVersion: v1
kind: Service
metadata:
  name: memcached-phpdocker-io-old
  namespace: phpdocker-io-old
  labels:
    app: memcached-phpdocker-io-old
spec:
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
  selector:
    app: memcached-phpdocker-io-old

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-phpdocker-io-old
  namespace: phpdocker-io-old
  labels:
    app: memcached-phpdocker-io-old
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: memcached-phpdocker-io-old
  template:
    metadata:
      labels:
        app: memcached-phpdocker-io-old
    spec:
      nodeSelector:
        preemptible: "false"
      containers:
        - image: memcached:alpine
          name: memcached
