# See https://github.com/idev4u/concourse-ci-kube
kind: Namespace
apiVersion: v1
metadata:
  name: phpdocker-io-old
  labels:
    name: phpdocker-io-old

---

apiVersion: v1
kind: Service
metadata:
  name: phpdocker-io-old
  namespace: phpdocker-io-old
  labels:
    app: phpdocker-io-old
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: phpdocker-io-old

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: phpdocker-io-old
  namespace: phpdocker-io-old
data:
  redis_host: "redis"
  redis_port: "6379"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpdocker-io-old
  namespace: phpdocker-io-old
  labels:
    app: phpdocker-io-old
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: phpdocker-io-old
  template:
    metadata:
      labels:
        app: phpdocker-io-old
    spec:
      containers:
        - image: eu.gcr.io/auron-infrastructure/phpdocker-old-nginx:latest
          name: nginx

        - image: eu.gcr.io/auron-infrastructure/phpdocker-old-php-fpm:latest
          name: php-fpm

          env:
            - name: APP_ENV
              value: prod

            - name: SYMFONY_ENV
              value: prod

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: phpdocker-io-old
                  key: app.secret

            - name: GOOGLE_ANALYTICS
              valueFrom:
                secretKeyRef:
                  name: phpdocker-io-old
                  key: google_analytics

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: phpdocker-io-old
                  key: redis_host

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: phpdocker-io-old
                  key: redis_port

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: phpdocker-io-old
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: phpdocker-io-old
  labels:
    app: redis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:alpine
          name: redis
