name: Run tests galore

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Initialise environment
        run: make prep-ci

      - name: Run behaviour tests
        run: make behaviour

      - name: Cleanup
        if: always()
        run: make clean
