name: Test

on:
  push:
    branches:
      - master
      - features/**
      - dependabot/**
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Initialise environment
        run: make prep-ci

      - name: Run behaviour tests
        run: make behaviour

      - name: Stop containers
        if: always()
        run: make clean
